<?xml version="1.0" encoding="utf-8" ?>
<!-- Copyright (c) .NET Foundation and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information. -->


<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <PropertyGroup>
    <SigningToolExe>C:\Program Files (x86)\Windows Kits\10\bin\x86\signtool.exe</SigningToolExe>
    <SigningCommand>sign</SigningCommand>
    <SigningConfiguration>/sha1 $(SigningHash) /d "WiX Toolset" /du "https://wixtoolset.org" /fd sha256 /td sha256 /tr "http://timestamp.digicert.com" </SigningConfiguration>

    <SigningFilelist>$(MSBuildThisFileDirectory)signing-filter.none.txt</SigningFilelist>
  </PropertyGroup>

  <ItemGroup>
    <!-- By default, $(TargetPath) will be signed. You can add files to @(FilesToSign) to sign them as well. -->
    <FilesToSign Include="$(TargetPath)" />
  </ItemGroup>

  <Target Name="SignFiles" AfterTargets="AfterBuild" Condition="'$(SignOutput)'=='true'">
    <Message Importance="high" Text="Signing file: %(FilesToSign.FullPath)" />

    <Exec Command='"$(SigningToolExe)" $(SigningCommand) $(SigningConfiguration) "%(FilesToSign.FullPath)"'
          WorkingDirectory="$(MSBuildProjectDirectory)" EchoOff="true"
          Condition="'%(FilesToSign.Extension)' != '.lib' And '%(FilesToSign.Extension)' != '.wixlib' And '%(FilesToSign.Extension)' != '.chm' And '%(FilesToSign.Filename)'  != 'burn' "/>
  </Target>

  <!--
  ================================================================================================

    Signing overrides to actually do signing. We don't sign the MSI packages or their CABs because
    they are always wrapped in a bundle that is signed.

  ================================================================================================
  -->
  <Target Name="SignCabs">
    <Exec Command='"$(SigningToolExe)" $(SigningCommand) $(SigningConfiguration) &quot;%(SignCabs.FullPath)&quot;"'
          WorkingDirectory="$(MSBuildProjectDirectory)" EchoOff="true" />
  </Target>

  <Target Name="SignMsi">
    <Exec Command='"$(SigningToolExe)" $(SigningCommand) $(SigningConfiguration) &quot;%(SignCabs.FullPath)&quot;"'
          WorkingDirectory="$(MSBuildProjectDirectory)" EchoOff="true" />
  </Target>

  <Target Name="SignContainers" />

  <Target Name="SignBundleEngine">
    <Message Importance="high" Text="Signing bundle engine: @(SignBundleEngine->&apos;%(Identity)&apos;)" />

    <Exec Command='"$(SigningToolExe)" $(SigningCommand) $(SigningConfiguration) "@(SignBundleEngine->&apos;%(Identity)&apos;)"'
          WorkingDirectory="$(MSBuildProjectDirectory)" EchoOff="true" />
  </Target>

  <Target Name="SignBundle">
    <Message Importance="high" Text="Signing bundle: @(SignBundle->&apos;%(Identity)&apos;)" />

    <Exec Command='"$(SigningToolExe)" $(SigningCommand) $(SigningConfiguration) "@(SignBundle->&apos;%(Identity)&apos;)"'
          WorkingDirectory="$(MSBuildProjectDirectory)" EchoOff="true" />
  </Target>

  <!-- Sentinel value that indicates WixBuid.Signing.targets has been initialized. -->
  <PropertyGroup>
    <WixBuildSigningTargetsDefined>true</WixBuildSigningTargetsDefined>
  </PropertyGroup>
</Project>
